//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:2.0.50727.3655
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 이 소스 코드가 Microsoft.CompactFramework.Design.Data, 버전 2.0.50727.3655에서 자동으로 생성되었습니다.
// 
namespace PackingManagement.MembershipService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IUserMembershipProvider", Namespace="Simmtech.User")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Organization))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserBase))]
    public partial class BasicHttpBinding_IUserMembershipProvider : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public BasicHttpBinding_IUserMembershipProvider() {
            this.Url = "http://localhost:8519/Simmtech/User/Membership";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Simmtech.User/IUserMembershipProvider/ChangePassword", RequestNamespace="Simmtech.User", ResponseNamespace="Simmtech.User", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ChangePassword([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string username, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string oldPassword, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string newPassword, out bool ChangePasswordResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool ChangePasswordResultSpecified) {
            object[] results = this.Invoke("ChangePassword", new object[] {
                        username,
                        oldPassword,
                        newPassword});
            ChangePasswordResult = ((bool)(results[0]));
            ChangePasswordResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginChangePassword(string username, string oldPassword, string newPassword, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ChangePassword", new object[] {
                        username,
                        oldPassword,
                        newPassword}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndChangePassword(System.IAsyncResult asyncResult, out bool ChangePasswordResult, out bool ChangePasswordResultSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            ChangePasswordResult = ((bool)(results[0]));
            ChangePasswordResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Simmtech.User/IUserMembershipProvider/ValidateUser", RequestNamespace="Simmtech.User", ResponseNamespace="Simmtech.User", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ValidateUser([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string username, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, out bool ValidateUserResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool ValidateUserResultSpecified) {
            object[] results = this.Invoke("ValidateUser", new object[] {
                        username,
                        password});
            ValidateUserResult = ((bool)(results[0]));
            ValidateUserResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginValidateUser(string username, string password, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ValidateUser", new object[] {
                        username,
                        password}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndValidateUser(System.IAsyncResult asyncResult, out bool ValidateUserResult, out bool ValidateUserResultSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            ValidateUserResult = ((bool)(results[0]));
            ValidateUserResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Simmtech.User/IUserMembershipProvider/GetUser", RequestNamespace="Simmtech.User", ResponseNamespace="Simmtech.User", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UserProfile GetUser([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string username) {
            object[] results = this.Invoke("GetUser", new object[] {
                        username});
            return ((UserProfile)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetUser(string username, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetUser", new object[] {
                        username}, callback, asyncState);
        }
        
        /// <remarks/>
        public UserProfile EndGetUser(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((UserProfile)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Simmtech.User/IUserMembershipProvider/GetOrganizations", RequestNamespace="Simmtech.User", ResponseNamespace="Simmtech.User", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Oraganization[] GetOrganizations() {
            object[] results = this.Invoke("GetOrganizations", new object[0]);
            return ((Oraganization[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetOrganizations(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetOrganizations", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public Oraganization[] EndGetOrganizations(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Oraganization[])(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IUserRoleProvider", Namespace="Simmtech.User")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Organization))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserBase))]
    public partial class BasicHttpBinding_IUserRoleProvider : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public BasicHttpBinding_IUserRoleProvider() {
            this.Url = "http://localhost:8519/Simmtech/User/Role";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Simmtech.User/IUserRoleProvider/AddUsersToRoles", RequestNamespace="Simmtech.User", ResponseNamespace="Simmtech.User", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddUsersToRoles([System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")] string[] usernames, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")] string[] roleNames) {
            this.Invoke("AddUsersToRoles", new object[] {
                        usernames,
                        roleNames});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAddUsersToRoles(string[] usernames, string[] roleNames, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AddUsersToRoles", new object[] {
                        usernames,
                        roleNames}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndAddUsersToRoles(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Simmtech.User/IUserRoleProvider/GetRolesForUser", RequestNamespace="Simmtech.User", ResponseNamespace="Simmtech.User", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] GetRolesForUser([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string username) {
            object[] results = this.Invoke("GetRolesForUser", new object[] {
                        username});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetRolesForUser(string username, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetRolesForUser", new object[] {
                        username}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndGetRolesForUser(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Simmtech.User")]
    public partial class UserProfile : UserBase {
        
        private string emailField;
        
        private System.DateTime endDateField;
        
        private bool endDateFieldSpecified;
        
        private Oraganization selectedOrganizationField;
        
        private System.DateTime startDateField;
        
        private bool startDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EndDateSpecified {
            get {
                return this.endDateFieldSpecified;
            }
            set {
                this.endDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Oraganization SelectedOrganization {
            get {
                return this.selectedOrganizationField;
            }
            set {
                this.selectedOrganizationField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartDateSpecified {
            get {
                return this.startDateFieldSpecified;
            }
            set {
                this.startDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Simmtech.User")]
    public partial class Oraganization : Organization {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Oraganization))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Simmtech.User")]
    public partial class Organization {
        
        private string codeField;
        
        private string descriptionField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private int operatingUnitIdField;
        
        private bool operatingUnitIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int OperatingUnitId {
            get {
                return this.operatingUnitIdField;
            }
            set {
                this.operatingUnitIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OperatingUnitIdSpecified {
            get {
                return this.operatingUnitIdFieldSpecified;
            }
            set {
                this.operatingUnitIdFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Simmtech.User")]
    public partial class UserValidation {
        
        private System.DateTime expiredField;
        
        private bool expiredFieldSpecified;
        
        private bool isLockedField;
        
        private bool isLockedFieldSpecified;
        
        private bool isModifiedField;
        
        private bool isModifiedFieldSpecified;
        
        private string passwordField;
        
        private System.DateTime passwordExpiredField;
        
        private bool passwordExpiredFieldSpecified;
        
        /// <remarks/>
        public System.DateTime Expired {
            get {
                return this.expiredField;
            }
            set {
                this.expiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpiredSpecified {
            get {
                return this.expiredFieldSpecified;
            }
            set {
                this.expiredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool IsLocked {
            get {
                return this.isLockedField;
            }
            set {
                this.isLockedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsLockedSpecified {
            get {
                return this.isLockedFieldSpecified;
            }
            set {
                this.isLockedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool IsModified {
            get {
                return this.isModifiedField;
            }
            set {
                this.isModifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsModifiedSpecified {
            get {
                return this.isModifiedFieldSpecified;
            }
            set {
                this.isModifiedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime PasswordExpired {
            get {
                return this.passwordExpiredField;
            }
            set {
                this.passwordExpiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PasswordExpiredSpecified {
            get {
                return this.passwordExpiredFieldSpecified;
            }
            set {
                this.passwordExpiredFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MembershipUser))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserProfile))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Simmtech.User")]
    public partial class UserBase {
        
        private string codeField;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string nameField;
        
        private string tokenField;
        
        private UserType typeField;
        
        private bool typeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public UserType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Simmtech.BusinessModel")]
    public enum UserType {
        
        /// <remarks/>
        None = 1,
        
        /// <remarks/>
        Employee = 2,
        
        /// <remarks/>
        Account = 4,
        
        /// <remarks/>
        All = 8,
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Simmtech.User")]
    public partial class MembershipUser : UserBase {
        
        private ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] propertiesField;
        
        private string[] rolesField;
        
        private UserValidation validateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfstringstring", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] Properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] Roles {
            get {
                return this.rolesField;
            }
            set {
                this.rolesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UserValidation Validate {
            get {
                return this.validateField;
            }
            set {
                this.validateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
    public partial class ArrayOfKeyValueOfstringstringKeyValueOfstringstring {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
}
